# Generated by Django 5.0.4 on 2024-05-07 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_remove_article_tag_article_tags'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='review',
            name='value',
        ),
    ]
