# Generated by Django 5.0.4 on 2024-05-12 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_alter_review_unique_together_remove_review_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
